package org.openhab.action.javarule.internal.rule;

import org.openhab.action.javarule.internal.AbstractItems;
import org.openhab.core.items.GroupItem;
import org.openhab.core.library.items.ColorItem;
import org.openhab.core.library.items.NumberItem;
import org.openhab.core.library.items.RollershutterItem;
import org.openhab.core.library.items.StringItem;
import org.openhab.core.library.items.SwitchItem;

public abstract class Items extends AbstractItems {

	// ========== copy generated code below ==========
	static GroupItem gFS20;
	static GroupItem gFS20Switches;
	static GroupItem gSwitch1;
	static SwitchItem sw2_1;
	static SwitchItem sw2_2;
	static GroupItem gSwitchBig;
	static SwitchItem sw1_1;
	static SwitchItem sw1_2;
	static SwitchItem sw1_3;
	static SwitchItem sw1_4;
	static SwitchItem sw1_5;
	static SwitchItem sw1_6;
	static SwitchItem sw1_7;
	static SwitchItem sw1_8;
	static GroupItem gKlingel;
	static SwitchItem klingel1;
	static GroupItem gShutter;
	static GroupItem gShutterUI;
	static GroupItem gShutWZ_West;
	static GroupItem gShutWZ_Sued;
	static SwitchItem shutGaeste;
	static SwitchItem shutBad;
	static SwitchItem shutSchlaf;
	static GroupItem gShutterWohn;
	static SwitchItem shutWZ_sued_kueche;
	static SwitchItem shutWZ_sued_links;
	static SwitchItem shutWZ_sued_rechts;
	static SwitchItem shutWZ_west_tuer;
	static SwitchItem shutWZ_west_links;
	static SwitchItem shutWZ_west_rechts;
	static SwitchItem shutWZ_spare;
	static SwitchItem shutALL;
	static RollershutterItem gShutWZ_WestUI;
	static RollershutterItem shutGaesteUI;
	static RollershutterItem shutSchlafUI;
	static RollershutterItem shutBadUI;
	static RollershutterItem shutWZ_sued_kuecheUI;
	static RollershutterItem shutWZ_sued_linksUI;
	static RollershutterItem shutWZ_sued_rechtsUI;
	static RollershutterItem shutWZ_west_tuerUI;
	static RollershutterItem shutWZ_west_linksUI;
	static RollershutterItem shutWZ_west_rechtsUI;
	static RollershutterItem shutWZ_suedUI;
	static RollershutterItem shutWZ_westUI;
	static GroupItem gHue;
	static GroupItem Switching;
	static GroupItem Lichter;
	static GroupItem Colorize;
	static GroupItem CTDimmer;
	static GroupItem WhiteDimmer;
	static GroupItem rGaeste;
	static GroupItem rBad;
	static GroupItem rSchlaf;
	static GroupItem rWohn;
	static GroupItem gTest;
	static NumberItem sceneWohnzimmer;
	static NumberItem sceneSchlafzimmer;
	static GroupItem gLichtWohnzimmer;
	static GroupItem gLichtSchlafzimmer;
	static ColorItem Color_1;
	static ColorItem Color_2;
	static ColorItem Color_3;
	static ColorItem Color_5;
	static SwitchItem Tap_1_1;
	static SwitchItem Tap_1_2;
	static SwitchItem Tap_1_3;
	static SwitchItem Tap_1_4;
	static SwitchItem Set_Tap_1_2;
	static SwitchItem Set_Tap_1_3;
	static SwitchItem Set_Tap_1_4;
	static GroupItem gIntertechno;
	static SwitchItem swTestIT;
	static SwitchItem swMarkise;
	static GroupItem gEvents;
	static SwitchItem testNotification;
	static SwitchItem testKlingel;
	static SwitchItem testTapRule;
	static SwitchItem setTapRules;
	static SwitchItem testJavaRule;
	static NumberItem Event_Chart_Period;
	static NumberItem alarmDelay;
	static StringItem alarmRemaining;
	static StringItem alarmEnd;
	static SwitchItem motion1;
	static SwitchItem motion2;
	static SwitchItem presence;
	static SwitchItem intrusion;
	static SwitchItem intrusionArmed;

	/**
	 * set items to values from item registry
	 */
	public static void setItems() {
		gFS20 = item("gFS20");
		gFS20Switches = item("gFS20Switches");
		gSwitch1 = item("gSwitch1");
		sw2_1 = item("sw2_1");
		sw2_2 = item("sw2_2");
		gSwitchBig = item("gSwitchBig");
		sw1_1 = item("sw1_1");
		sw1_2 = item("sw1_2");
		sw1_3 = item("sw1_3");
		sw1_4 = item("sw1_4");
		sw1_5 = item("sw1_5");
		sw1_6 = item("sw1_6");
		sw1_7 = item("sw1_7");
		sw1_8 = item("sw1_8");
		gKlingel = item("gKlingel");
		klingel1 = item("klingel1");
		gShutter = item("gShutter");
		gShutterUI = item("gShutterUI");
		gShutWZ_West = item("gShutWZ_West");
		gShutWZ_Sued = item("gShutWZ_Sued");
		shutGaeste = item("shutGaeste");
		shutBad = item("shutBad");
		shutSchlaf = item("shutSchlaf");
		gShutterWohn = item("gShutterWohn");
		shutWZ_sued_kueche = item("shutWZ_sued_kueche");
		shutWZ_sued_links = item("shutWZ_sued_links");
		shutWZ_sued_rechts = item("shutWZ_sued_rechts");
		shutWZ_west_tuer = item("shutWZ_west_tuer");
		shutWZ_west_links = item("shutWZ_west_links");
		shutWZ_west_rechts = item("shutWZ_west_rechts");
		shutWZ_spare = item("shutWZ_spare");
		shutALL = item("shutALL");
		gShutWZ_WestUI = item("gShutWZ_WestUI");
		shutGaesteUI = item("shutGaesteUI");
		shutSchlafUI = item("shutSchlafUI");
		shutBadUI = item("shutBadUI");
		shutWZ_sued_kuecheUI = item("shutWZ_sued_kuecheUI");
		shutWZ_sued_linksUI = item("shutWZ_sued_linksUI");
		shutWZ_sued_rechtsUI = item("shutWZ_sued_rechtsUI");
		shutWZ_west_tuerUI = item("shutWZ_west_tuerUI");
		shutWZ_west_linksUI = item("shutWZ_west_linksUI");
		shutWZ_west_rechtsUI = item("shutWZ_west_rechtsUI");
		shutWZ_suedUI = item("shutWZ_suedUI");
		shutWZ_westUI = item("shutWZ_westUI");
		gHue = item("gHue");
		Switching = item("Switching");
		Lichter = item("Lichter");
		Colorize = item("Colorize");
		CTDimmer = item("CTDimmer");
		WhiteDimmer = item("WhiteDimmer");
		rGaeste = item("rGaeste");
		rBad = item("rBad");
		rSchlaf = item("rSchlaf");
		rWohn = item("rWohn");
		gTest = item("gTest");
		sceneWohnzimmer = item("sceneWohnzimmer");
		sceneSchlafzimmer = item("sceneSchlafzimmer");
		gLichtWohnzimmer = item("gLichtWohnzimmer");
		gLichtSchlafzimmer = item("gLichtSchlafzimmer");
		Color_1 = item("Color_1");
		Color_2 = item("Color_2");
		Color_3 = item("Color_3");
		Color_5 = item("Color_5");
		Tap_1_1 = item("Tap_1_1");
		Tap_1_2 = item("Tap_1_2");
		Tap_1_3 = item("Tap_1_3");
		Tap_1_4 = item("Tap_1_4");
		Set_Tap_1_2 = item("Set_Tap_1_2");
		Set_Tap_1_3 = item("Set_Tap_1_3");
		Set_Tap_1_4 = item("Set_Tap_1_4");
		gIntertechno = item("gIntertechno");
		swTestIT = item("swTestIT");
		swMarkise = item("swMarkise");
		gTest = item("gTest");
		gEvents = item("gEvents");
		testNotification = item("testNotification");
		testKlingel = item("testKlingel");
		testTapRule = item("testTapRule");
		setTapRules = item("setTapRules");
		testJavaRule = item("testJavaRule");
		Event_Chart_Period = item("Event_Chart_Period");
		alarmDelay = item("alarmDelay");
		alarmRemaining = item("alarmRemaining");
		alarmEnd = item("alarmEnd");
		motion1 = item("motion1");
		motion2 = item("motion2");
		presence = item("presence");
		intrusion = item("intrusion");
		intrusionArmed = item("intrusionArmed");
	}
	// ========== END: generated code ==========
}
