package org.openhab.action.javarule.internal.rule;

import org.openhab.action.javarule.internal.AbstractItems;
import org.openhab.action.javarule.items.ColorItemProxy;
import org.openhab.action.javarule.items.GroupItemProxy;
import org.openhab.action.javarule.items.NumberItemProxy;
import org.openhab.action.javarule.items.RollershutterItemProxy;
import org.openhab.action.javarule.items.StringItemProxy;
import org.openhab.action.javarule.items.SwitchItemProxy;

public abstract class Items extends AbstractItems {

	// ========== copy generated code below ==========
	static GroupItemProxy gFS20;
	static GroupItemProxy gFS20Switches;
	static GroupItemProxy gSwitch1;
	static SwitchItemProxy sw2_1;
	static SwitchItemProxy sw2_2;
	static GroupItemProxy gSwitchBig;
	static SwitchItemProxy sw1_1;
	static SwitchItemProxy sw1_2;
	static SwitchItemProxy sw1_3;
	static SwitchItemProxy sw1_4;
	static SwitchItemProxy sw1_5;
	static SwitchItemProxy sw1_6;
	static SwitchItemProxy sw1_7;
	static SwitchItemProxy sw1_8;
	static GroupItemProxy gKlingel;
	static SwitchItemProxy klingel1;
	static GroupItemProxy gShutter;
	static GroupItemProxy gShutterUI;
	static GroupItemProxy gShutWZ_West;
	static GroupItemProxy gShutWZ_Sued;
	static SwitchItemProxy shutGaeste;
	static SwitchItemProxy shutBad;
	static SwitchItemProxy shutSchlaf;
	static GroupItemProxy gShutterWohn;
	static SwitchItemProxy shutWZ_sued_kueche;
	static SwitchItemProxy shutWZ_sued_links;
	static SwitchItemProxy shutWZ_sued_rechts;
	static SwitchItemProxy shutWZ_west_tuer;
	static SwitchItemProxy shutWZ_west_links;
	static SwitchItemProxy shutWZ_west_rechts;
	static SwitchItemProxy shutWZ_spare;
	static SwitchItemProxy shutALL;
	static RollershutterItemProxy gShutWZ_WestUI;
	static RollershutterItemProxy shutGaesteUI;
	static RollershutterItemProxy shutSchlafUI;
	static RollershutterItemProxy shutBadUI;
	static RollershutterItemProxy shutWZ_sued_kuecheUI;
	static RollershutterItemProxy shutWZ_sued_linksUI;
	static RollershutterItemProxy shutWZ_sued_rechtsUI;
	static RollershutterItemProxy shutWZ_west_tuerUI;
	static RollershutterItemProxy shutWZ_west_linksUI;
	static RollershutterItemProxy shutWZ_west_rechtsUI;
	static RollershutterItemProxy shutWZ_suedUI;
	static RollershutterItemProxy shutWZ_westUI;
	static GroupItemProxy gHue;
	static GroupItemProxy Switching;
	static GroupItemProxy Lichter;
	static GroupItemProxy Colorize;
	static GroupItemProxy CTDimmer;
	static GroupItemProxy WhiteDimmer;
	static GroupItemProxy rGaeste;
	static GroupItemProxy rBad;
	static GroupItemProxy rSchlaf;
	static GroupItemProxy rWohn;
	static GroupItemProxy gTest;
	static NumberItemProxy sceneWohnzimmer;
	static NumberItemProxy sceneSchlafzimmer;
	static GroupItemProxy gLichtWohnzimmer;
	static GroupItemProxy gLichtSchlafzimmer;
	public static ColorItemProxy Color_1;
	static ColorItemProxy Color_2;
	static ColorItemProxy Color_3;
	static ColorItemProxy Color_5;
	static SwitchItemProxy Tap_1_1;
	static SwitchItemProxy Tap_1_2;
	static SwitchItemProxy Tap_1_3;
	static SwitchItemProxy Tap_1_4;
	static SwitchItemProxy Set_Tap_1_2;
	static SwitchItemProxy Set_Tap_1_3;
	static SwitchItemProxy Set_Tap_1_4;
	static GroupItemProxy gIntertechno;
	static SwitchItemProxy swTestIT;
	static SwitchItemProxy swMarkise;
	static GroupItemProxy gEvents;
	static SwitchItemProxy testNotification;
	static SwitchItemProxy testKlingel;
	static SwitchItemProxy testTapRule;
	static SwitchItemProxy setTapRules;
	static SwitchItemProxy testJavaRule;
	static NumberItemProxy Event_Chart_Period;
	static NumberItemProxy alarmDelay;
	static StringItemProxy alarmRemaining;
	static StringItemProxy alarmEnd;
	static SwitchItemProxy motion1;
	static SwitchItemProxy motion2;
	static SwitchItemProxy presence;
	static SwitchItemProxy intrusion;
	static SwitchItemProxy intrusionArmed;

	// ========== END: generated code ==========
}
